/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.LLamada;
import clases.Recarga;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author aolivero11
 */
public class AgregarRecarga extends javax.swing.JDialog {

    /**
     * Creates new form Agrega
     */
    String rutaL, rutaR;
    ObjectOutputStream salida;
    LinkedList<Recarga> recargas;
    int aux = 0;
    TableRowSorter trsFiltro;

    public AgregarRecarga(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JButton botonesH[] = {cmdCancelar, cmdGuardar,};
        JButton botonesD[] = {cmdEliminar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        rutaL = "src/datos/llamadas.txt";
        rutaR = "src/datos/recargas.txt";
        Helper.llenarComboLlamadas(cmbCdg, rutaL);
        try {
            recargas = Helper.traerDatos(rutaR);
            salida = new ObjectOutputStream(new FileOutputStream(rutaR));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, recargas);
        Helper.llenarTablaRecargas(tblTablaPrincipal, rutaR);
    }

    public void filtro() {
        int columnaABuscar = 0;
        if (cmbBuscador.getSelectedItem() == "Codigo") {
            columnaABuscar = 1;
        }
        if (cmbBuscador.getSelectedItem() == "Operador") {
            columnaABuscar = 2;
        }
        if (cmbBuscador.getSelectedItem() == "Valor") {
            columnaABuscar = 3;
        }
        if (cmbBuscador.getSelectedItem() == "Tipo de Pago") {
            columnaABuscar = 4;
        }
        trsFiltro.setRowFilter(RowFilter.regexFilter(txtFiltro.getText(), columnaABuscar));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbPago = new javax.swing.ButtonGroup();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        cmdEliminar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTablaPrincipal = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbCdg = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        rbEfectivo = new javax.swing.JRadioButton();
        rbCredito = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbBuscador = new javax.swing.JComboBox<String>();
        txtFiltro = new javax.swing.JTextField();
        cbBuscar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AGREGAR RECARGAS");

        jPanel9.setBackground(new java.awt.Color(255, 255, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 4));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones\n", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdEliminar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel11.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        cmdCancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel11.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 30));

        cmdGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel11.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 170, 200));

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Llamadas:", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTablaPrincipal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tblTablaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Código", "Operador", "Valor", "Tipo de Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTablaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaPrincipalMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTablaPrincipal);
        if (tblTablaPrincipal.getColumnModel().getColumnCount() > 0) {
            tblTablaPrincipal.getColumnModel().getColumn(0).setResizable(false);
            tblTablaPrincipal.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblTablaPrincipal.getColumnModel().getColumn(1).setResizable(false);
            tblTablaPrincipal.getColumnModel().getColumn(2).setResizable(false);
            tblTablaPrincipal.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel12.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 470, 280));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 500, 320));

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos principales:", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Código:");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });
        jPanel10.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 100, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Valor de la recarga:");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        cmbCdg.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel10.add(cmbCdg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 180, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Tipo de Pago:");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        rbPago.add(rbEfectivo);
        rbEfectivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbEfectivo.setText("Efectivo");
        rbEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEfectivoActionPerformed(evt);
            }
        });
        jPanel10.add(rbEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        rbPago.add(rbCredito);
        rbCredito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbCredito.setText("Crédito");
        rbCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCreditoActionPerformed(evt);
            }
        });
        jPanel10.add(rbCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 200));

        jPanel13.setBackground(new java.awt.Color(255, 255, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Buscar por:");
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        cmbBuscador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmbBuscador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Operador", "Valor", "Tipo de Pago" }));
        cmbBuscador.setEnabled(false);
        jPanel13.add(cmbBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 110, -1));

        txtFiltro.setEnabled(false);
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });
        jPanel13.add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 160, 30));

        cbBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuscarActionPerformed(evt);
            }
        });
        jPanel13.add(cbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 500, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(555, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        txtFiltro.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtFiltro.getText());
                txtFiltro.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tblTablaPrincipal.getModel());
        tblTablaPrincipal.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyTyped

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int i, op;
        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar esta llamada?", "Eliminar", JOptionPane.YES_NO_OPTION);

        LinkedList<Recarga> recarga = Helper.traerDatos(rutaR);
        if (op == JOptionPane.YES_OPTION) {
            i = tblTablaPrincipal.getSelectedRow();
            recarga.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(rutaR));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Agrega.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Agrega.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.volcado(salida, recarga);
            Helper.llenarTablaRecargas(tblTablaPrincipal, rutaR);

            cmbCdg.setSelectedIndex(0);
            txtValor.setText("");
            txtValor.requestFocusInWindow();
        }
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        txtValor.setText("");
        cmbCdg.setSelectedIndex(0);
        txtValor.requestFocusInWindow();

        JButton botonesH[] = {cmdCancelar, cmdGuardar};
        JButton botonesD[] = {cmdEliminar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void tblTablaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaPrincipalMouseClicked
        int i;
        String auxCdg;
        Recarga r;
        LLamada cdg;
        LinkedList<Recarga> recarga = Helper.traerDatos(rutaR);
        i = tblTablaPrincipal.getSelectedRow();

        r = recarga.get(i);

        txtValor.setText(r.getValor());
        cdg = r.getCodop();
        auxCdg = cdg.getCodigo() + " - " + cdg.getOperador();
        cmbCdg.setSelectedItem(auxCdg);
        aux = 1;

        JButton botonesH[] = {cmdEliminar, cmdCancelar, cmdGuardar};
        JButton botonesD[] = {};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);

    }//GEN-LAST:event_tblTablaPrincipalMouseClicked

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        String auxCdg, codigo, valor, pago;
        int indice;
        LLamada cdg;

        if (txtValor.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Dijite el valor de la recarga!", 3);
            txtValor.requestFocusInWindow();
        } else if (rbEfectivo.isSelected() == false && rbCredito.isSelected() == false) {
            Helper.mensaje(this, "¡Escoja una opcion de pago!", 3);
        } else {

            valor = txtValor.getText();
            pago = "";
            if (rbEfectivo.isSelected() == true) {
                pago = "Efectivo";
            } else if (rbCredito.isSelected() == true) {
                pago = "Crédito";
            }
            auxCdg = cmbCdg.getSelectedItem().toString();
            indice = auxCdg.indexOf("-") - 1;
            codigo = auxCdg.substring(0, indice);
            cdg = Helper.traerLlamadaCodigo(codigo, rutaL);
            LinkedList<Recarga> recargaModificado;
            try {
               
                    Recarga r = new Recarga(valor, cdg, pago);
                    r.guardar(salida);
                
            } catch (IOException ex) {
                Logger.getLogger(AgregarRecarga.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.llenarTablaRecargas(tblTablaPrincipal, rutaR);
            txtValor.setText("");
            cmbCdg.setSelectedIndex(0);
            txtValor.requestFocusInWindow();

            JButton botonesH[] = {cmdCancelar, cmdEliminar};
            JButton botonesD[] = {};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuscarActionPerformed
        if (cbBuscar.isSelected() == true) {
            cmbBuscador.setEnabled(true);
            txtFiltro.setEnabled(true);
        } else {
            cmbBuscador.setEnabled(false);
            txtFiltro.setEnabled(false);
        }
    }//GEN-LAST:event_cbBuscarActionPerformed

    private void rbEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEfectivoActionPerformed

    }//GEN-LAST:event_rbEfectivoActionPerformed

    private void rbCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCreditoActionPerformed

    }//GEN-LAST:event_rbCreditoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarRecarga dialog = new AgregarRecarga(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbBuscar;
    private javax.swing.JComboBox<String> cmbBuscador;
    private javax.swing.JComboBox<String> cmbCdg;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbEfectivo;
    public static javax.swing.ButtonGroup rbPago;
    private javax.swing.JTable tblTablaPrincipal;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
